name: Flask CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pytest

    - name: Build Docker image
      run: docker build -t flask-devops-app .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Docker image
      run: docker tag flask-devops-app docker.io/${{ secrets.DOCKER_USERNAME }}/flask-devops-app:latest

    - name: Push Docker image to Docker Hub
      run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/flask-devops-app:latest

    - name: Trigger Deploy on Render
      run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
